# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_hr',
            field=models.BooleanField(default=False, verbose_name='\u5e10\u53f7\u662f\u5426\u5c5e\u4e8eHR'),
        ),
    ]
