# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, verbose_name='verification token')),
                ('expire_time', models.DateTimeField(verbose_name='token\u5931\u6548\u65f6\u95f4')),
                ('is_used', models.BooleanField(default=False, verbose_name='token\u662f\u5426\u5df2\u7ecf\u88ab\u4f7f\u7528\u8fc7')),
                ('is_verified', models.BooleanField(default=False, verbose_name='token\u662f\u5426\u5df2\u7ecf\u88ab\u6807\u8bb0\u4e3a\u9a8c\u8bc1\u901a\u8fc7')),
            ],
            options={
                'verbose_name': 'verification token',
                'verbose_name_plural': 'verification token',
            },
        ),
    ]
