# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='mobile_ip',
            field=models.CharField(max_length=15, null=True, verbose_name='\u6388\u6743\u65f6\u7684\u624b\u673aip\u5730\u5740'),
        ),
    ]
