# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, verbose_name='MAC\u5730\u5740')),
                ('ip', models.CharField(max_length=15, null=True, verbose_name='\u5728\u7ebf\u65f6\u7684ip\u5730\u5740')),
                ('date', models.DateField(verbose_name='\u5728\u7ebf\u8bb0\u5f55\u7684\u65e5\u671f')),
                ('time', models.TimeField(verbose_name='\u5728\u7ebf\u8bb0\u5f55\u7684\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u5728\u7ebf\u8bb0\u5f55',
                'verbose_name_plural': '\u5728\u7ebf\u8bb0\u5f55',
            },
        ),
    ]
